# Generated by Django 4.2.4 on 2024-10-24 16:05

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('race', models.CharField(max_length=20)),
                ('class_field', models.CharField(db_column='class', max_length=14)),
                ('description', models.CharField(max_length=1000)),
                ('features', models.CharField(max_length=150)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('photo_url', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'character',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterToRequest',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('coordinate_x', models.IntegerField(blank=True, null=True)),
                ('coordinate_y', models.IntegerField(blank=True, null=True)),
                ('friendorenemy', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'character_to_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=10)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('map_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='Разрешения')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', stocks.models.NewUserManager()),
            ],
        ),
    ]
